apiVersion: v1
kind: Pod
metadata:
  name: pod-apache
  namespace: default
spec:
  containers:
  - name: my-apache     #10.244.0.91
    image: httpd
---
apiVersion: v1
kind: Pod
metadata:
  name: pode-nginx
  namespace: default
spec:
  containers:      
  - name: my-nginx    #10.244.0.92
    image: nginx

