apiVersion: v1
kind: Pod
metadata:
  name: resources-pod
spec:
  containers:
  - name: apache-container
    image: httpd
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"       
      requests:
        cpu: "0.3"
        memory: "64Mi"
      

        
